from typing import *

# current_page
JsonDict = NewType('JsonDict', Dict[str, List[Any]])
# current_page_illusts = current_page['illusts']
JsonDictPage = NewType('JsonDictPage', List[Dict[str, Any]])
# post_json = current_page_illusts[i]
PostJson = NewType('PostJson', Dict[str, Any])
# all_pages_cache = {str page_num: JsonDict current_page}
Cache = NewType('Cache', Dict[str, JsonDict])

def async_download_spinner(download_path: str, urls: List[str], rename_images: bool, file_names: Optional[List[str]], pbar: Optional[Any]) -> None: ...
def async_download_core(download_path: str, urls: List[str], rename_images: bool, file_names: Optional[List[str]], pbar: Optional[Any]) -> None: ...
def downloadr(url: str, img_name: str, new_file_name: Optional[str], pbar: Optional[Any]) -> None: ...
def download_page(current_page_illusts: JsonDictPage, current_page_num: int, artist_user_id: int, pbar: Optional[Any]) -> None: ...
def download_core(large_dir: str, url: str, filename: str, try_make_dir: bool) -> None: ...
def download_image_verified(image_id: Optional[int], post_json: Optional[PostJson], png: bool, **kwargs: Any) -> None: ...
