from typing import *
from blessed import Terminal
import koneko

TERM: Terminal

def ask_quit() -> None: ...
def gallery_like_prompt(gallery_like_class: koneko.AbstractGallery) -> None: ...
def image_prompt(image: koneko.Image) -> None: ...
def user_prompt(user_class: koneko.Users) -> None: ...
