from typing import *

# current_page
JsonDict = NewType('JsonDict', Dict[str, List[Any]])
# current_page_illusts = current_page['illusts']
JsonDictPage = NewType('JsonDictPage', List[Dict[str, Any]])
# post_json = current_page_illusts[i]
PostJson = NewType('PostJson', Dict[str, Any])

def cd(newdir: str) -> None: ...
def spin(done: bool, message: Optional[str]) -> None: ...
def split_backslash_last(string: str) -> str: ...
def generate_filepath(filename: str) -> str: ...
def prefix_filename(old_name: str, new_name: str, number: int) -> str: ...
def prefix_artist_name(name: str, number: int) -> str: ...
def find_number_map(x: int, y: int) -> Union[int, bool]: ...
def print_multiple_imgs(illusts_json: JsonDictPage) -> None: ...
def url_given_size(post_json: PostJson, size: str) -> str: ...
def post_title(current_page_illusts: JsonDictPage, post_number: int) -> str: ...
def medium_urls(current_page_illusts: JsonDictPage) -> List[str]: ...
def post_titles_in_page(current_page_illusts: JsonDictPage) -> List[str]: ...
def page_urls_in_post(post_json: PostJson, size: str) -> Tuple[int, List[str]]: ...
def change_url_to_full(post_json: Optional[PostJson], png: Optional[bool], url: Optional[str]) -> str: ...
def catch_ctrl_c(call: Any): ...
