from typing import *

def verify_full_download(filepath: str) -> bool: ...
def show_artist_illusts(path: str, renderer: str, **kwargs: Any) -> None: ...
def display_image_vp(filepath: str) -> None: ...
def begin_prompt(printmessage: bool) -> str: ...
def artist_user_id_prompt() -> str: ...
def show_man_loop() -> None: ...
def clear_cache_loop() -> None: ...
def info_screen_loop() -> None: ...
